// @page aircraft-market AircraftMarketPage "Aircraft"
// Generated by `node tools/page/airiona.mjs scaffold aircraft-market` from docs/pages/aircraft-market/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ArAppBar, ArButton, ArChipScroller, ArIconButton, ArMiniDestination, ArSearchField, ArSelect, ArStayCard, ArTabBar, ArTopNav, type ArOption, type ArSelectOption, type ArTabItem, type ArTopNavLink, type ArTopNavUser } from '@airiona/ui';
import { AIRCRAFTMARKET_SAMPLE } from './aircraft-market.data';

/** Aircraft. Primary action: Open an aircraft listing. */
@Component({
  selector: 'pg-aircraft-market',
  imports: [ArAppBar, ArButton, ArChipScroller, ArIconButton, ArMiniDestination, ArSearchField, ArSelect, ArStayCard, ArTabBar, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './aircraft-market.page.html',
  styleUrl: './aircraft-market.page.css',
})
export class AircraftMarketPage {
  protected readonly data = AIRCRAFTMARKET_SAMPLE;

  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "book",
      "label": "Book"
    },
    {
      "value": "trips",
      "label": "My trips"
    },
    {
      "value": "aircraft",
      "label": "Aircraft"
    },
    {
      "value": "hangars",
      "label": "Hangars"
    }
  ];
  protected readonly topNavUser: ArTopNavUser = {
    "name": "Omar Saleh",
    "email": "omar@example.com"
  };
  protected readonly sortOptions: Array<string | ArSelectOption> = [
    {
      "value": "new",
      "label": "Newest"
    },
    {
      "value": "price-asc",
      "label": "Price: low to high"
    },
    {
      "value": "price-desc",
      "label": "Price: high to low"
    },
    {
      "value": "hours",
      "label": "Fewest hours"
    }
  ];
  protected readonly categoryOptions: Array<string | ArOption> = [
    {
      "value": "all",
      "label": "All"
    },
    {
      "value": "heavy",
      "label": "Heavy jets"
    },
    {
      "value": "midsize",
      "label": "Midsize"
    },
    {
      "value": "light",
      "label": "Light jets"
    },
    {
      "value": "turboprop",
      "label": "Turboprops"
    },
    {
      "value": "heli",
      "label": "Helicopters"
    }
  ];
  protected readonly tabBarItems: ArTabItem[] = [
    {
      "value": "home",
      "label": "Home",
      "icon": "home"
    },
    {
      "value": "book",
      "label": "Book",
      "icon": "paper-airplane"
    },
    {
      "value": "aircraft",
      "label": "Aircraft",
      "icon": "rocket-launch"
    },
    {
      "value": "hangars",
      "label": "Hangars",
      "icon": "building-office-2"
    },
    {
      "value": "account",
      "label": "Account",
      "icon": "user-circle"
    }
  ];
  protected listAircraft(event: unknown): void {
    // Owners are the other side of the marketplace; the sell door stays in the header
    console.info('listAircraft', event);
  }

  protected openFilters(event: unknown): void {
    // Debounce 300ms, then GET with ?q=
    console.info('openFilters', event);
  }

  protected openListing(event: unknown): void {
    // Routes to the detail page; the heart saves to the watchlist
    console.info('openListing', event);
  }

  protected openHangars(event: unknown): void {
    // Compact photo cards that peek on phones; a door into the other marketplace
    console.info('openHangars', event);
  }
}
