// @page aircraft-detail AircraftDetailPage "Aircraft"
// Generated by `node tools/page/airiona.mjs scaffold aircraft-detail` from docs/pages/aircraft-detail/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ArAmenityList, ArButton, ArCheckbox, ArDetailList, ArDialog, ArExpandableText, ArInfoStatRow, ArMobileSegmented, ArPlaceHero, ArStickyActionBar, ArSuccessBurst, ArTextField, ArTopNav, type ArAmenity, type ArDetailItem, type ArInfoStat, type ArOption, type ArTopNavLink, type ArTopNavUser } from '@airiona/ui';
import { pageForm } from '../../shared/page-form';
import { phone } from '../../shared/validators';
import { AIRCRAFTDETAIL_SAMPLE } from './aircraft-detail.data';

/** Aircraft. Primary action: Contact the seller. */
@Component({
  selector: 'pg-aircraft-detail',
  imports: [ReactiveFormsModule, ArAmenityList, ArButton, ArCheckbox, ArDetailList, ArDialog, ArExpandableText, ArInfoStatRow, ArMobileSegmented, ArPlaceHero, ArStickyActionBar, ArSuccessBurst, ArTextField, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './aircraft-detail.page.html',
  styleUrl: './aircraft-detail.page.css',
})
export class AircraftDetailPage {
  private readonly fb = inject(FormBuilder);
  protected readonly data = AIRCRAFTDETAIL_SAMPLE;
  protected readonly enquiry = this.fb.group({
    fullName: ["", [Validators.required, Validators.maxLength(80)]],
    email: ["", [Validators.required, Validators.email]],
    phone: ["", [Validators.required, phone]],
    intent: ["buy", [Validators.required]],
    message: ["", [Validators.maxLength(500)]],
    financing: [false, []],
  });
  protected readonly enquiryForm = pageForm(this.enquiry, {
    "fullName": {
      "required": "Enter your name.",
      "maxlength": "Names are at most 80 characters."
    },
    "email": {
      "required": "Enter your email.",
      "email": "Enter an email like name@example.com."
    },
    "phone": {
      "required": "Enter a phone number.",
      "phone": "Enter a number with its country code, like +971 50 123 4567."
    },
    "intent": {
      "required": "Choose what you want to do."
    },
    "message": {
      "maxlength": "Keep it under 500 characters."
    },
    "financing": {}
  });
  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "book",
      "label": "Book"
    },
    {
      "value": "trips",
      "label": "My trips"
    },
    {
      "value": "aircraft",
      "label": "Aircraft"
    },
    {
      "value": "hangars",
      "label": "Hangars"
    }
  ];
  protected readonly topNavUser: ArTopNavUser = {
    "name": "Omar Saleh",
    "email": "omar@example.com"
  };
  protected readonly factRowItems: ArInfoStat[] = [
    {
      "icon": "clock",
      "label": "4,210 hrs"
    },
    {
      "icon": "user-group",
      "label": "16 seats"
    },
    {
      "icon": "calendar",
      "label": "2016"
    },
    {
      "icon": "globe-alt",
      "label": "6,750 nm"
    }
  ];
  protected readonly specListItems: ArDetailItem[] = [
    {
      "label": "Serial number",
      "value": "5530"
    },
    {
      "label": "Registration",
      "value": "A6-ARN"
    },
    {
      "label": "Total time",
      "value": "4,210 hours"
    },
    {
      "label": "Landings",
      "value": "1,870"
    },
    {
      "label": "Engines",
      "value": "2 × Rolls-Royce BR710 C4-11"
    },
    {
      "label": "Engine programme",
      "value": "CorporateCare Enhanced"
    },
    {
      "label": "Avionics",
      "value": "Honeywell PlaneView, EVS II"
    },
    {
      "label": "Last inspection",
      "value": "72-month, Mar 2026"
    }
  ];
  protected readonly amenityListItems: ArAmenity[] = [
    {
      "icon": "wifi",
      "label": "Ka-band Wi-Fi"
    },
    {
      "icon": "moon",
      "label": "6 berths"
    },
    {
      "icon": "tv",
      "label": "Cabin screens"
    },
    {
      "icon": "fire",
      "label": "Full galley"
    },
    {
      "icon": "sparkles",
      "label": "Shower"
    },
    {
      "icon": "shield-check",
      "label": "No damage history"
    }
  ];
  protected readonly intentOptions: Array<string | ArOption> = [
    {
      "value": "buy",
      "label": "Buy"
    },
    {
      "value": "lease",
      "label": "Lease"
    },
    {
      "value": "charter",
      "label": "Charter"
    }
  ];
  protected readonly enquiryDone = signal(false);
  protected submitEnquiry(): void {
    this.enquiryForm.submit((value) => {
      // POST /api/aircraft/g550/enquiries { fullName, email, phone, intent, message, financing }. On failure: Network or 5xx: danger Toast with Retry, the form stays filled; 429: Toast asking to wait a minute
      console.info('enquiry submit', value);
      this.enquiryDone.set(true);
    });
  }

  protected listAircraft(event: unknown): void {
    // The sell door stays in the header
    console.info('listAircraft', event);
  }

  protected goBack(event: unknown): void {
    // Full-width photo with glass back and bookmark buttons and a plate with the name, place and price: the system detail header
    console.info('goBack', event);
  }
}
