// @page flight-booking FlightBookingPage "Book a flight"
// Generated by `node tools/page/airiona.mjs scaffold flight-booking` from docs/pages/flight-booking/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ArAppBar, ArBadge, ArButton, ArCheckbox, ArDatePicker, ArDetailList, ArDialog, ArIconButton, ArInfoStatRow, ArMobileSegmented, ArOptionList, ArQuantityStepper, ArRouteHeader, ArSegmentedControl, ArSelect, ArStickyActionBar, ArSuccessBurst, ArTextField, ArTopNav, type ArDatePreset, type ArInfoStat, type ArOption, type ArTopNavLink, type ArTopNavUser } from '@airiona/ui';
import { pageForm } from '../../shared/page-form';
import { futureDate, phone } from '../../shared/validators';
import { FLIGHTBOOKING_SAMPLE } from './flight-booking.data';

/** Book a flight. Primary action: Request the flight on the chosen aircraft. */
@Component({
  selector: 'pg-flight-booking',
  imports: [ReactiveFormsModule, ArAppBar, ArBadge, ArButton, ArCheckbox, ArDatePicker, ArDetailList, ArDialog, ArIconButton, ArInfoStatRow, ArMobileSegmented, ArOptionList, ArQuantityStepper, ArRouteHeader, ArSegmentedControl, ArSelect, ArStickyActionBar, ArSuccessBurst, ArTextField, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './flight-booking.page.html',
  styleUrl: './flight-booking.page.css',
})
export class FlightBookingPage {
  private readonly fb = inject(FormBuilder);
  protected readonly data = FLIGHTBOOKING_SAMPLE;
  protected readonly booking = this.fb.group({
    tripType: ["one", [Validators.required]],
    from: ["DXB", [Validators.required]],
    to: ["LTN", [Validators.required]],
    departure: ["2026-10-15", [Validators.required, futureDate()]],
    passengers: [4, [Validators.min(1), Validators.max(19)]],
    aircraft: [null as unknown, [Validators.required]],
    fullName: ["", [Validators.required, Validators.minLength(3), Validators.maxLength(80)]],
    email: ["", [Validators.required, Validators.email]],
    phone: ["", [Validators.required, phone]],
    requests: ["", [Validators.maxLength(500)]],
    terms: [false, [Validators.requiredTrue]],
  });
  protected readonly bookingForm = pageForm(this.booking, {
    "tripType": {
      "required": "Choose one way or return."
    },
    "from": {
      "required": "Choose where you fly from."
    },
    "to": {
      "required": "Choose where you fly to."
    },
    "departure": {
      "required": "Choose a departure date.",
      "futureDate": "Departure can't be in the past."
    },
    "passengers": {
      "min": "At least one passenger flies.",
      "max": "For more than 19 passengers, talk to a broker."
    },
    "aircraft": {
      "required": "Choose the aircraft you want."
    },
    "fullName": {
      "required": "Enter the lead passenger's name as on the passport.",
      "minlength": "Enter the full name.",
      "maxlength": "Use at most 80 characters."
    },
    "email": {
      "required": "Enter an email for the confirmation.",
      "email": "Enter an email like name@example.com."
    },
    "phone": {
      "required": "Enter a phone number the crew can reach.",
      "phone": "Enter a phone number with country code, like +971 50 123 4567."
    },
    "requests": {
      "maxlength": "Keep requests under 500 characters."
    },
    "terms": {
      "required": "Tick to agree before requesting."
    }
  });
  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "book",
      "label": "Book"
    },
    {
      "value": "trips",
      "label": "My trips"
    },
    {
      "value": "aircraft",
      "label": "Aircraft"
    },
    {
      "value": "hangars",
      "label": "Hangars"
    }
  ];
  protected readonly topNavUser: ArTopNavUser = {
    "name": "Omar Saleh",
    "email": "omar@example.com"
  };
  protected readonly tripTypeOptions: Array<string | ArOption> = [
    {
      "value": "one",
      "label": "One way"
    },
    {
      "value": "return",
      "label": "Return"
    }
  ];
  protected readonly tripTypeDesktopOptions: Array<string | ArOption> = [
    {
      "value": "one",
      "label": "One way"
    },
    {
      "value": "return",
      "label": "Return"
    }
  ];
  protected readonly departurePresets: ArDatePreset[] = [
    {
      "label": "Tomorrow",
      "value": "2026-10-04"
    },
    {
      "label": "This Friday",
      "value": "2026-10-09"
    }
  ];
  protected readonly flightFactsItems: ArInfoStat[] = [
    {
      "icon": "clock",
      "label": "7 h 25 m"
    },
    {
      "icon": "users",
      "label": "4 of 9 seats"
    },
    {
      "icon": "briefcase",
      "label": "10 bags"
    }
  ];
  protected readonly bookingDone = signal(false);
  protected submitBooking(): void {
    this.bookingForm.submit((value) => {
      // POST /api/charter/requests { offerId, tripType, from, to, departure, passengers, leadPassenger, requests }. On failure: Offer no longer available (410): Toast 'That aircraft was just booked' and the offers refresh; any other error: danger Toast with Retry and the form kept
      console.info('booking submit', value);
      this.bookingDone.set(true);
    });
  }
}
