// @page login LoginPage "Sign in"
// Generated by `node tools/page/airiona.mjs scaffold login` from docs/pages/login/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ArAuthShell, ArButton, ArCheckbox, ArTextField, type ArAuthHighlight } from '@airiona/ui';
import { pageForm } from '../../shared/page-form';
import { LOGIN_SAMPLE } from './login.data';

/** Sign in. Primary action: Sign in with email and password. */
@Component({
  selector: 'pg-login',
  imports: [ReactiveFormsModule, ArAuthShell, ArButton, ArCheckbox, ArTextField],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './login.page.html',
  styleUrl: './login.page.css',
})
export class LoginPage {
  private readonly fb = inject(FormBuilder);
  protected readonly data = LOGIN_SAMPLE;
  protected readonly login = this.fb.group({
    email: ["", [Validators.required, Validators.email, Validators.maxLength(254)]],
    password: ["", [Validators.required, Validators.minLength(8)]],
    remember: [false, []],
  });
  protected readonly loginForm = pageForm(this.login, {
    "email": {
      "required": "Enter your email.",
      "email": "Enter an email like name@example.com.",
      "maxlength": "Emails are at most 254 characters."
    },
    "password": {
      "required": "Enter your password.",
      "minlength": "Passwords are at least 8 characters."
    },
    "remember": {}
  });
  protected readonly shellHighlights: ArAuthHighlight[] = [
    {
      "title": "All-in prices",
      "text": "Crew, fuel, airport fees and VAT in one number before you request."
    },
    {
      "title": "Confirmed in minutes",
      "text": "Operators answer a request within the 15-minute price hold."
    },
    {
      "title": "Hangars on the same account",
      "text": "Book space at 140 airports for the aircraft you fly or own."
    }
  ];
  protected readonly emailPlaceholder: string = "name@example.com";
  private readonly router = inject(Router);
  protected submitLogin(): void {
    this.loginForm.submit((value) => {
      // POST /api/auth/session { email, password, remember }. On failure: 401: danger Toast 'That email and password don't match.' and clear only the password; 429: Toast 'Too many tries. Wait a minute and try again.' with the button disabled for the wait
      console.info('login submit', value);
      void this.router.navigateByUrl("/flight-home");
    });
  }

  protected openHelp(event: unknown): void {
    // Opens the help centre in a new tab
    console.info('openHelp', event);
  }

  protected signInWithPasskey(event: unknown): void {
    // navigator.credentials.get with the WebAuthn challenge from POST /api/auth/passkey/challenge
    console.info('signInWithPasskey', event);
  }
}
