// @page login LoginPage "Log in"
// Generated by `node tools/page/airiona.mjs scaffold login` from docs/pages/login/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ArAppBar, ArButton, ArCheckbox, ArHeroHeader, ArTextField, ArTopNav, type ArTopNavLink } from '@airiona/ui';
import { pageForm } from '../../shared/page-form';
import { LOGIN_SAMPLE } from './login.data';

/** Log in. Primary action: Sign in with email and password. */
@Component({
  selector: 'pg-login',
  imports: [ReactiveFormsModule, ArAppBar, ArButton, ArCheckbox, ArHeroHeader, ArTextField, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './login.page.html',
  styleUrl: './login.page.css',
})
export class LoginPage {
  private readonly fb = inject(FormBuilder);
  protected readonly data = LOGIN_SAMPLE;
  protected readonly login = this.fb.group({
    email: ["", [Validators.required, Validators.email, Validators.maxLength(254)]],
    password: ["", [Validators.required, Validators.minLength(8)]],
    remember: [false, []],
  });
  protected readonly loginForm = pageForm(this.login, {
    "email": {
      "required": "Enter the email you signed up with.",
      "email": "Enter an email like name@example.com.",
      "maxlength": "Emails are at most 254 characters."
    },
    "password": {
      "required": "Enter your password.",
      "minlength": "Passwords are at least 8 characters."
    },
    "remember": {}
  });
  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "home",
      "label": "Home"
    },
    {
      "value": "services",
      "label": "Services"
    },
    {
      "value": "features",
      "label": "Features"
    },
    {
      "value": "team",
      "label": "Team"
    }
  ];
  protected readonly emailPlaceholder: string = "name@example.com";
  private readonly router = inject(Router);
  protected submitLogin(): void {
    this.loginForm.submit((value) => {
      // POST /api/auth/session { email, password, remember }. On failure: 401: danger Toast ‘That email and password don't match.’ and clear only the password; 429: Toast ‘Too many tries. Wait a minute and try again.’ with the button disabled for the wait
      console.info('login submit', value);
      void this.router.navigateByUrl("/");
    });
  }

  protected goToSignup(event: unknown): void {
    // Routes to /signup
    console.info('goToSignup', event);
  }
}
