// @page hangar-market HangarMarketPage "Hangars"
// Generated by `node tools/page/airiona.mjs scaffold hangar-market` from docs/pages/hangar-market/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ArAppBar, ArButton, ArChipScroller, ArIconButton, ArMiniDestination, ArSearchField, ArSelect, ArStayCard, ArTabBar, ArTopNav, type ArOption, type ArSelectOption, type ArTabItem, type ArTopNavLink, type ArTopNavUser } from '@airiona/ui';
import { HANGARMARKET_SAMPLE } from './hangar-market.data';

/** Hangars. Primary action: Open a hangar listing. */
@Component({
  selector: 'pg-hangar-market',
  imports: [ArAppBar, ArButton, ArChipScroller, ArIconButton, ArMiniDestination, ArSearchField, ArSelect, ArStayCard, ArTabBar, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './hangar-market.page.html',
  styleUrl: './hangar-market.page.css',
})
export class HangarMarketPage {
  protected readonly data = HANGARMARKET_SAMPLE;

  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "book",
      "label": "Book"
    },
    {
      "value": "trips",
      "label": "My trips"
    },
    {
      "value": "aircraft",
      "label": "Aircraft"
    },
    {
      "value": "hangars",
      "label": "Hangars"
    }
  ];
  protected readonly topNavUser: ArTopNavUser = {
    "name": "Omar Saleh",
    "email": "omar@example.com"
  };
  protected readonly sortOptions: Array<string | ArSelectOption> = [
    {
      "value": "near",
      "label": "Nearest"
    },
    {
      "value": "price-asc",
      "label": "Price: low to high"
    },
    {
      "value": "door",
      "label": "Widest door"
    },
    {
      "value": "rating",
      "label": "Top rated"
    }
  ];
  protected readonly categoryOptions: Array<string | ArOption> = [
    {
      "value": "all",
      "label": "All"
    },
    {
      "value": "heavy",
      "label": "Heavy jets"
    },
    {
      "value": "midsize",
      "label": "Midsize"
    },
    {
      "value": "light",
      "label": "Light jets"
    },
    {
      "value": "heli",
      "label": "Helicopters"
    },
    {
      "value": "nightly",
      "label": "Nightly"
    }
  ];
  protected readonly tabBarItems: ArTabItem[] = [
    {
      "value": "home",
      "label": "Home",
      "icon": "home"
    },
    {
      "value": "book",
      "label": "Book",
      "icon": "paper-airplane"
    },
    {
      "value": "aircraft",
      "label": "Aircraft",
      "icon": "rocket-launch"
    },
    {
      "value": "hangars",
      "label": "Hangars",
      "icon": "building-office-2"
    },
    {
      "value": "account",
      "label": "Account",
      "icon": "user-circle"
    }
  ];
  protected listHangar(event: unknown): void {
    // Hangar hosts are the supply side; listing space stays one tap away
    console.info('listHangar', event);
  }

  protected openFilters(event: unknown): void {
    // Debounce 300ms, then GET with ?q=
    console.info('openFilters', event);
  }

  protected openListing(event: unknown): void {
    // Routes to the detail page; the heart saves to the watchlist
    console.info('openListing', event);
  }

  protected openAircraft(event: unknown): void {
    // Compact photo cards that peek on phones; a door into the other marketplace
    console.info('openAircraft', event);
  }
}
