// @page stay-checkout StayCheckoutPage "Stay checkout"
// Generated by `node tools/page/airiona.mjs scaffold stay-checkout` from docs/pages/stay-checkout/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ArAppBar, ArBadge, ArBookingSteps, ArButton, ArCheckbox, ArDatePicker, ArDetailList, ArDialog, ArInfoStatRow, ArMiniDestination, ArPlaceCard, ArQuantityStepper, ArSelect, ArStickyActionBar, ArSuccessBurst, ArTextField, ArTopNav, type ArInfoStat, type ArTopNavLink, type ArTopNavUser } from '@airiona/ui';
import { pageForm } from '../../shared/page-form';
import { dateRange, futureDate, phone } from '../../shared/validators';
import { STAYCHECKOUT_SAMPLE } from './stay-checkout.data';

/** Stay checkout. Primary action: Pay and confirm the stay. */
@Component({
  selector: 'pg-stay-checkout',
  imports: [ReactiveFormsModule, ArAppBar, ArBadge, ArBookingSteps, ArButton, ArCheckbox, ArDatePicker, ArDetailList, ArDialog, ArInfoStatRow, ArMiniDestination, ArPlaceCard, ArQuantityStepper, ArSelect, ArStickyActionBar, ArSuccessBurst, ArTextField, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './stay-checkout.page.html',
  styleUrl: './stay-checkout.page.css',
})
export class StayCheckoutPage {
  private readonly fb = inject(FormBuilder);
  protected readonly data = STAYCHECKOUT_SAMPLE;
  protected readonly booking = this.fb.group({
    dates: [["2026-10-15","2026-10-19"], [Validators.required, dateRange, futureDate()]],
    adults: [2, [Validators.min(1)]],
    children: [0, []],
    firstName: ["", [Validators.required, Validators.maxLength(60)]],
    lastName: ["", [Validators.required, Validators.maxLength(60)]],
    email: ["", [Validators.required, Validators.email]],
    phone: ["", [Validators.required, phone]],
    country: [null as unknown, [Validators.required]],
    terms: [false, [Validators.requiredTrue]],
  });
  protected readonly bookingForm = pageForm(this.booking, {
    "dates": {
      "required": "Choose check-in and check-out.",
      "dateRange": "Check-out must be after check-in.",
      "futureDate": "Check-in can't be in the past."
    },
    "adults": {
      "min": "At least one adult has to stay."
    },
    "children": {},
    "firstName": {
      "required": "Enter the first name as on the passport.",
      "maxlength": "Use at most 60 characters."
    },
    "lastName": {
      "required": "Enter the last name as on the passport.",
      "maxlength": "Use at most 60 characters."
    },
    "email": {
      "required": "Enter your email so we can send the booking.",
      "email": "Enter an email like name@example.com."
    },
    "phone": {
      "required": "Enter a phone number the host can reach.",
      "phone": "Enter a phone number with country code, like +49 30 1234567."
    },
    "country": {
      "required": "Choose your country of residence."
    },
    "terms": {
      "required": "Tick to agree before paying."
    }
  });
  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "flights",
      "label": "Flights"
    },
    {
      "value": "stays",
      "label": "Stays"
    },
    {
      "value": "trips",
      "label": "Trips"
    }
  ];
  protected readonly topNavUser: ArTopNavUser = {
    "name": "Maya Haddad",
    "email": "maya@example.com"
  };
  protected readonly progressSteps: string[] = [
    "Search",
    "Select",
    "Details",
    "Pay",
    "Done"
  ];
  protected readonly factsItems: ArInfoStat[] = [
    {
      "icon": "calendar-days",
      "label": "15–19 Oct"
    },
    {
      "icon": "users",
      "label": "2 guests"
    },
    {
      "icon": "moon",
      "label": "4 nights"
    }
  ];
  protected readonly bookingDone = signal(false);
  protected submitBooking(): void {
    this.bookingForm.submit((value) => {
      // POST /api/bookings { stayId, dates, adults, children, traveller, paymentIntentId }. On failure: Payment declined: danger Toast with the provider's message and the form kept; price changed (409): Dialog showing old and new total with Continue and Cancel
      console.info('booking submit', value);
      this.bookingDone.set(true);
    });
  }

  protected backToStay(event: unknown): void {
    // Navigates to /stays/:id
    console.info('backToStay', event);
  }
}
