// @page hangar-detail HangarDetailPage "Hangar"
// Generated by `node tools/page/airiona.mjs scaffold hangar-detail` from docs/pages/hangar-detail/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ArAmenityList, ArButton, ArDatePicker, ArDetailList, ArDialog, ArExpandableText, ArInfoStatRow, ArPlaceHero, ArRatingBreakdown, ArSelect, ArStickyActionBar, ArSuccessBurst, ArTextField, ArTopNav, type ArAmenity, type ArDetailItem, type ArInfoStat, type ArRatingSegment, type ArSelectOption, type ArTopNavLink, type ArTopNavUser } from '@airiona/ui';
import { pageForm } from '../../shared/page-form';
import { dateRange, futureDate, phone } from '../../shared/validators';
import { HANGARDETAIL_SAMPLE } from './hangar-detail.data';

/** Hangar. Primary action: Request hangar space. */
@Component({
  selector: 'pg-hangar-detail',
  imports: [ReactiveFormsModule, ArAmenityList, ArButton, ArDatePicker, ArDetailList, ArDialog, ArExpandableText, ArInfoStatRow, ArPlaceHero, ArRatingBreakdown, ArSelect, ArStickyActionBar, ArSuccessBurst, ArTextField, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './hangar-detail.page.html',
  styleUrl: './hangar-detail.page.css',
})
export class HangarDetailPage {
  private readonly fb = inject(FormBuilder);
  protected readonly data = HANGARDETAIL_SAMPLE;
  protected readonly lease = this.fb.group({
    aircraftSize: [null as unknown, [Validators.required]],
    registration: ["", [Validators.required, Validators.pattern("^[A-Za-z0-9]{1,2}-?[A-Za-z0-9]{2,5}$")]],
    leaseDates: [null as unknown, [Validators.required, dateRange, futureDate()]],
    fullName: ["", [Validators.required, Validators.maxLength(80)]],
    email: ["", [Validators.required, Validators.email]],
    phone: ["", [Validators.required, phone]],
  });
  protected readonly leaseForm = pageForm(this.lease, {
    "aircraftSize": {
      "required": "Choose your aircraft size."
    },
    "registration": {
      "required": "Enter the registration.",
      "pattern": "Enter a registration like A6-ARN or N550GA."
    },
    "leaseDates": {
      "required": "Choose your dates.",
      "dateRange": "Choose a move-out date after move-in.",
      "futureDate": "Dates must be in the future."
    },
    "fullName": {
      "required": "Enter your name.",
      "maxlength": "Names are at most 80 characters."
    },
    "email": {
      "required": "Enter your email.",
      "email": "Enter an email like name@example.com."
    },
    "phone": {
      "required": "Enter a phone number.",
      "phone": "Enter a number with its country code, like +971 50 123 4567."
    }
  });
  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "book",
      "label": "Book"
    },
    {
      "value": "trips",
      "label": "My trips"
    },
    {
      "value": "aircraft",
      "label": "Aircraft"
    },
    {
      "value": "hangars",
      "label": "Hangars"
    }
  ];
  protected readonly topNavUser: ArTopNavUser = {
    "name": "Omar Saleh",
    "email": "omar@example.com"
  };
  protected readonly factRowItems: ArInfoStat[] = [
    {
      "icon": "arrows-right-left",
      "label": "38 m door"
    },
    {
      "icon": "arrows-up-down",
      "label": "11 m height"
    },
    {
      "icon": "square-3-stack-3d",
      "label": "2,900 m²"
    },
    {
      "icon": "sun",
      "label": "Climate"
    }
  ];
  protected readonly specListItems: ArDetailItem[] = [
    {
      "label": "Door width",
      "value": "38 m"
    },
    {
      "label": "Clear height",
      "value": "11 m"
    },
    {
      "label": "Floor area",
      "value": "2,900 m²"
    },
    {
      "label": "Largest aircraft",
      "value": "Global 7500, G700"
    },
    {
      "label": "Ground power",
      "value": "400 Hz at every bay"
    },
    {
      "label": "Fire protection",
      "value": "Foam deluge, NFPA 409"
    },
    {
      "label": "Access",
      "value": "24/7, logged"
    },
    {
      "label": "Minimum term",
      "value": "1 month"
    }
  ];
  protected readonly amenityListItems: ArAmenity[] = [
    {
      "icon": "sun",
      "label": "Climate control"
    },
    {
      "icon": "bolt",
      "label": "Ground power"
    },
    {
      "icon": "shield-check",
      "label": "24/7 security"
    },
    {
      "icon": "wrench-screwdriver",
      "label": "Line maintenance"
    },
    {
      "icon": "truck",
      "label": "Towing included"
    },
    {
      "icon": "sparkles",
      "label": "Weekly wash"
    }
  ];
  protected readonly ratingSegments: ArRatingSegment[] = [
    {
      "label": "Excellent",
      "value": 81
    },
    {
      "label": "Good",
      "value": 14
    },
    {
      "label": "Average",
      "value": 4
    },
    {
      "label": "Poor",
      "value": 1
    }
  ];
  protected readonly aircraftSizeOptions: Array<string | ArSelectOption> = [
    {
      "value": "heli",
      "label": "Helicopter"
    },
    {
      "value": "light",
      "label": "Light jet"
    },
    {
      "value": "midsize",
      "label": "Midsize or super-midsize jet"
    },
    {
      "value": "heavy",
      "label": "Heavy or ultra-long-range jet"
    }
  ];
  protected readonly leaseDone = signal(false);
  protected submitLease(): void {
    this.leaseForm.submit((value) => {
      // POST /api/hangars/dwc-4/requests { aircraftSize, registration, leaseDates, fullName, email, phone }. On failure: 409 (dates taken): message under the dates 'Those dates were just booked. Pick another range.'; network: danger Toast with Retry
      console.info('lease submit', value);
      this.leaseDone.set(true);
    });
  }

  protected listHangar(event: unknown): void {
    // The host door stays in the header
    console.info('listHangar', event);
  }

  protected goBack(event: unknown): void {
    // Full-width photo with glass back and bookmark buttons and a plate with the name, place and price: the system detail header
    console.info('goBack', event);
  }
}
