// Generated by `node tools/page/airiona.mjs scaffold <page>`. Do not edit by hand.
import { Routes } from '@angular/router';

export const PAGE_ROUTES: Routes = [
  { path: 'flight-home', title: "Flight home", loadComponent: () => import('./flight-home/flight-home.page').then((m) => m.FlightHomePage) },
  { path: 'login', title: "Log in", loadComponent: () => import('./login/login.page').then((m) => m.LoginPage) },
];
