// @page flight-home FlightHomePage "Flight home"
// Generated by `node tools/page/airiona.mjs scaffold flight-home` from docs/pages/flight-home/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ArAppBar, ArButton, ArDatePicker, ArDestinationCard, ArFeatureCard, ArHeroHeader, ArMiniDestination, ArMobileSegmented, ArSegmentedControl, ArSelect, ArTopNav, type ArOption, type ArTopNavLink } from '@airiona/ui';
import { pageForm } from '../../shared/page-form';
import { dateRange, futureDate } from '../../shared/validators';
import { FLIGHTHOME_SAMPLE } from './flight-home.data';

/** Flight home. Primary action: Search flights for a route and dates. */
@Component({
  selector: 'pg-flight-home',
  imports: [ReactiveFormsModule, ArAppBar, ArButton, ArDatePicker, ArDestinationCard, ArFeatureCard, ArHeroHeader, ArMiniDestination, ArMobileSegmented, ArSegmentedControl, ArSelect, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './flight-home.page.html',
  styleUrl: './flight-home.page.css',
})
export class FlightHomePage {
  private readonly fb = inject(FormBuilder);
  protected readonly data = FLIGHTHOME_SAMPLE;
  protected readonly search = this.fb.group({
    tripType: ["round", [Validators.required]],
    from: [null as unknown, [Validators.required]],
    to: [null as unknown, [Validators.required]],
    dates: [null as unknown, [Validators.required, dateRange, futureDate()]],
  });
  protected readonly searchForm = pageForm(this.search, {
    "tripType": {
      "required": "Choose one way, round trip or multi-city."
    },
    "from": {
      "required": "Choose the airport you are flying from."
    },
    "to": {
      "required": "Choose where you want to fly to."
    },
    "dates": {
      "required": "Choose your departure and return dates.",
      "dateRange": "Pick a return date after your departure.",
      "futureDate": "Departure must be today or later."
    }
  });
  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "flights",
      "label": "Flights"
    },
    {
      "value": "hotels",
      "label": "Hotels"
    },
    {
      "value": "trains",
      "label": "Trains"
    },
    {
      "value": "buses",
      "label": "Buses"
    },
    {
      "value": "cabs",
      "label": "Cabs"
    }
  ];
  protected readonly tripTypeOptions: Array<string | ArOption> = [
    {
      "value": "one",
      "label": "One way"
    },
    {
      "value": "round",
      "label": "Round trip"
    },
    {
      "value": "multi",
      "label": "Multi-city"
    }
  ];
  protected readonly tripTypeDesktopOptions: Array<string | ArOption> = [
    {
      "value": "one",
      "label": "One way"
    },
    {
      "value": "round",
      "label": "Round trip"
    },
    {
      "value": "multi",
      "label": "Multi-city"
    }
  ];
  private readonly router = inject(Router);
  protected submitSearch(): void {
    this.searchForm.submit((value) => {
      // GET /api/flights/search?from&to&depart&return&trip (the app navigates to the results route with the same query). On failure: Network or 5xx: danger Toast 'Could not search right now. Check your connection and try again.' with Retry; the form stays filled. 422 (no route): message under the To field 'We don't fly this route yet.'
      console.info('search submit', value);
      void this.router.navigateByUrl("/flights/results");
    });
  }

  protected goToSignIn(event: unknown): void {
    // Routes to /login
    console.info('goToSignIn', event);
  }

  protected openDeal(event: unknown): void {
    // The source's cabin photo is not shown: FeatureCard has no image input (logged under gaps as a proposal, not a GAP element, because the card still conveys the deal).
    console.info('openDeal', event);
  }

  protected openAirline(event: unknown): void {
    // A compact photo card with a name and three small facts; the carousel peeks the next card like the source
    console.info('openAirline', event);
  }

  protected bookHotel(event: unknown): void {
    // A photo card with name, star rating, a distance line and a small Book now button is exactly the source's hotel card
    console.info('bookHotel', event);
  }
}
