// @page flight-home FlightHomePage "Home"
// Generated by `node tools/page/airiona.mjs scaffold flight-home` from docs/pages/flight-home/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ArAppBar, ArBookingSearch, ArButton, ArFeatureCard, ArMiniDestination, ArPlaceCard, ArPromoBanner, ArSectionHeader, ArSplitHero, ArStatStrip, ArTabBar, ArTopNav, type ArSplitBadge, type ArStripStat, type ArTabItem, type ArTopNavLink } from '@airiona/ui';
import { FLIGHTHOME_SAMPLE } from './flight-home.data';

/** Home. Primary action: Search a route and open the booking page. */
@Component({
  selector: 'pg-flight-home',
  imports: [ArAppBar, ArBookingSearch, ArButton, ArFeatureCard, ArMiniDestination, ArPlaceCard, ArPromoBanner, ArSectionHeader, ArSplitHero, ArStatStrip, ArTabBar, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './flight-home.page.html',
  styleUrl: './flight-home.page.css',
})
export class FlightHomePage {
  protected readonly data = FLIGHTHOME_SAMPLE;

  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "explore",
      "label": "Explore"
    },
    {
      "value": "destinations",
      "label": "Destinations"
    },
    {
      "value": "aircraft",
      "label": "Aircraft"
    },
    {
      "value": "hangars",
      "label": "Hangars"
    },
    {
      "value": "deals",
      "label": "Deals"
    }
  ];
  protected readonly splitHeroBadge: ArSplitBadge | null = {
    "value": "28K+",
    "title": "Happy flyers",
    "text": "joined this year",
    "people": [
      {
        "name": "Lina Haddad",
        "src": "assets/photos/people/traveller-1.webp"
      },
      {
        "name": "Omar Saleh",
        "src": "assets/photos/people/traveller-2.webp"
      },
      {
        "name": "Mei Tanaka",
        "src": "assets/photos/people/traveller-3.webp"
      }
    ]
  };
  protected readonly statsItems: ArStripStat[] = [
    {
      "icon": "globe-alt",
      "value": "140",
      "label": "Airports"
    },
    {
      "icon": "paper-airplane",
      "value": "1,240",
      "label": "Aircraft",
      "tone": "green"
    },
    {
      "icon": "users",
      "value": "28K+",
      "label": "Happy flyers",
      "tone": "amber"
    }
  ];
  protected readonly tabBarItems: ArTabItem[] = [
    {
      "value": "home",
      "label": "Home",
      "icon": "home"
    },
    {
      "value": "book",
      "label": "Book",
      "icon": "paper-airplane"
    },
    {
      "value": "aircraft",
      "label": "Aircraft",
      "icon": "rocket-launch"
    },
    {
      "value": "hangars",
      "label": "Hangars",
      "icon": "building-office-2"
    },
    {
      "value": "account",
      "label": "Account",
      "icon": "user-circle"
    }
  ];
  protected goToSignIn(event: unknown): void {
    // Routes to /login
    console.info('goToSignIn', event);
  }

  protected openLanguage(event: unknown): void {
    // Opens a language Menu (English, العربية)
    console.info('openLanguage', event);
  }

  protected openStory(event: unknown): void {
    // The ring button opens a Dialog with the full brand film (not part of this page). The loop is 5.25s, 555 KB, H.264; the poster is its first frame.
    console.info('openStory', event);
  }

  protected goToBooking(event: unknown): void {
    // Routes to /flight-booking
    console.info('goToBooking', event);
  }

  protected searchFlights(event: unknown): void {
    // Search navigates to /flight-booking with from, to, dates and travellers in the query
    console.info('searchFlights', event);
  }

  protected openSearchField(event: unknown): void {
    // Search navigates to /flight-booking with from, to, dates and travellers in the query
    console.info('openSearchField', event);
  }

  protected openDeals(event: unknown): void {
    // The reference's limited-offer photo card
    console.info('openDeals', event);
  }

  protected openDestinations(event: unknown): void {
    // Title with the reference's View all link
    console.info('openDestinations', event);
  }

  protected openDestination(event: unknown): void {
    // The reference's tall photo card with a heart, the name, a from-price and the rating
    console.info('openDestination', event);
  }

  protected openMarketplace(event: unknown): void {
    // Compact photo cards with three short facts; each opens its marketplace
    console.info('openMarketplace', event);
  }
}
