// Builds @airiona/react from design-system/components/bundle.js (the React reference implementation).
// Output: packages/react/dist/{index.mjs,index.cjs,index.d.ts,airiona.umd.js} + packages/react/styles/*.
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync, execSync } from 'node:child_process';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'design-system/components');
const PKG = join(ROOT, 'packages/react');
const DIST = join(PKG, 'dist');

execFileSync(process.execPath, [join(ROOT, 'tools/sync-design-system.mjs')], { stdio: 'inherit' });
// The typings ship as written: type-check them first (a syntax slip here breaks every consumer's build).
execSync('npx tsc --noEmit --strict design-system/components/index.d.ts', { stdio: 'inherit', cwd: ROOT });

const umd = readFileSync(join(SRC, 'bundle.js'), 'utf8').replace(/\r\n/g, '\n');
const names = JSON.parse(/@ds-bundle: (\{.*?\}) \*\//.exec(umd)[1]).components.map((c) => c.name);

/** Rewrites the browser-global bundle so React and ReactDOM come from module imports. */
function moduleBody(src) {
  const replacements = [
    ['var React = window.React;', 'var React = __React;'],
    ['!window.ReactDOM || !window.ReactDOM.createPortal', '!__ReactDOM || !__ReactDOM.createPortal'],
    ['window.ReactDOM.createPortal(', '__ReactDOM.createPortal('],
    ['window.Airiona = Object.assign(window.Airiona || {}, api);', '__api = api;'],
  ];
  let out = src;
  for (const [from, to] of replacements) {
    if (!out.includes(from)) throw new Error(`build-react: pattern not found: ${from}`);
    out = out.split(from).join(to);
  }
  if (/window\.React\b|window\.Airiona/.test(out)) throw new Error('build-react: unrewritten global React/Airiona reference left');
  return out;
}

const body = moduleBody(umd);
const header = '/* @airiona/react — generated by tools/build-react.mjs from design-system/components/bundle.js. Do not edit. */\n';
const esm = `${header}import * as __ReactNs from 'react';\nimport * as __ReactDOMNs from 'react-dom';\nvar __React = __ReactNs.default || __ReactNs;\nvar __ReactDOM = __ReactDOMNs.default || __ReactDOMNs;\nvar __api;\n${body}\nexport default __api;\nexport const { ${names.join(', ')}, motion } = __api;\n`;
const cjs = `${header}'use strict';\nvar __React = require('react');\nvar __ReactDOM = require('react-dom');\nvar __api;\n${body}\nmodule.exports = __api;\nmodule.exports.default = __api;\n`;

rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
writeFileSync(join(DIST, 'index.mjs'), esm);
writeFileSync(join(DIST, 'index.cjs'), cjs);
writeFileSync(join(DIST, 'airiona.umd.js'), umd);
writeFileSync(join(DIST, 'index.d.ts'), readFileSync(join(SRC, 'index.d.ts'), 'utf8'));
writeFileSync(join(PKG, 'styles/airiona.css'), '/* Airiona for React. Import once: import "@airiona/react/styles/airiona.css" */\n@import "./tokens.css";\n@import "./components.css";\n');
cpSync(join(ROOT, 'design-system/assets'), join(PKG, 'assets'), { recursive: true });
console.log(`built @airiona/react: ${names.length} components`);
