// @page operator-dashboard OperatorDashboardPage "Operator dashboard"
// Generated by `node tools/page/airiona.mjs scaffold operator-dashboard` from docs/pages/operator-dashboard/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ArAppBar, ArBalanceChart, ArButton, ArDataTable, ArIconButton, ArLeaderboard, ArPageHeader, ArSegmentGauge, ArStatCard, ArTabBar, ArTopNav, type ArBalanceTooltip, type ArGaugeSegment, type ArLeaderboardItem, type ArOption, type ArTabItem, type ArTableColumn, type ArTopNavLink, type ArTopNavUser } from '@airiona/ui';
import { OPERATORDASHBOARD_SAMPLE } from './operator-dashboard.data';

/** Operator dashboard. Primary action: Open a booking that needs action. */
@Component({
  selector: 'pg-operator-dashboard',
  imports: [ArAppBar, ArBalanceChart, ArButton, ArDataTable, ArIconButton, ArLeaderboard, ArPageHeader, ArSegmentGauge, ArStatCard, ArTabBar, ArTopNav],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './operator-dashboard.page.html',
  styleUrl: './operator-dashboard.page.css',
})
export class OperatorDashboardPage {
  protected readonly data = OPERATORDASHBOARD_SAMPLE;

  protected readonly topNavLinks: ArTopNavLink[] = [
    {
      "value": "dashboard",
      "label": "Dashboard"
    },
    {
      "value": "requests",
      "label": "Requests"
    },
    {
      "value": "fleet",
      "label": "Fleet"
    },
    {
      "value": "hangars",
      "label": "Hangars"
    }
  ];
  protected readonly topNavUser: ArTopNavUser = {
    "name": "Gulf Executive Aviation",
    "email": "ops@gulfexec.example"
  };
  protected readonly pageHeaderTabs: Array<string | ArOption> = [
    {
      "value": "month",
      "label": "This month"
    },
    {
      "value": "quarter",
      "label": "Quarter"
    },
    {
      "value": "year",
      "label": "Year"
    }
  ];
  protected readonly revenueChartBars: number[] = [
    520,
    610,
    580,
    720,
    690,
    810,
    760,
    880,
    940,
    1120,
    1080,
    1280
  ];
  protected readonly revenueChartYLabels: string[] = [
    "$1.4M",
    "$1M",
    "$500k",
    "0"
  ];
  protected readonly revenueChartSelection: [number, number] = [
    8,
    11
  ];
  protected readonly revenueChartTooltip: ArBalanceTooltip = {
    "value": "$1.28M",
    "date": "Oct 2026"
  };
  protected readonly revenueChartRanges: string[] = [
    "3M",
    "6M",
    "YTD",
    "1Y"
  ];
  protected readonly utilisationSegments: ArGaugeSegment[] = [
    {
      "label": "Flying",
      "value": 46,
      "display": "46%"
    },
    {
      "label": "Positioning",
      "value": 14,
      "display": "14%"
    },
    {
      "label": "Maintenance",
      "value": 12,
      "display": "12%"
    },
    {
      "label": "Idle",
      "value": 28,
      "display": "28%"
    }
  ];
  protected readonly topAircraftItems: ArLeaderboardItem[] = [
    {
      "name": "G550 · A6-ARN",
      "role": "Heavy jet",
      "score": "$412k",
      "label": "revenue"
    },
    {
      "name": "Praetor 600 · A6-PRT",
      "role": "Super-midsize",
      "score": "$318k",
      "label": "revenue"
    },
    {
      "name": "Latitude · A6-LAT",
      "role": "Midsize",
      "score": "$264k",
      "label": "revenue",
      "roleTone": "success"
    }
  ];
  protected readonly bookingTableColumns: ArTableColumn[] = [
    {
      "key": "id",
      "header": "Reference",
      "sortable": true
    },
    {
      "key": "client",
      "header": "Client",
      "sortable": true
    },
    {
      "key": "route",
      "header": "Route"
    },
    {
      "key": "aircraft",
      "header": "Aircraft"
    },
    {
      "key": "date",
      "header": "Date",
      "sortable": true
    },
    {
      "key": "status",
      "header": "Status",
      "sortable": true
    },
    {
      "key": "total",
      "header": "Total",
      "sortable": true
    }
  ];
  protected readonly tabBarItems: ArTabItem[] = [
    {
      "value": "dashboard",
      "label": "Home",
      "icon": "squares-2x2"
    },
    {
      "value": "requests",
      "label": "Requests",
      "icon": "inbox",
      "badge": true
    },
    {
      "value": "fleet",
      "label": "Fleet",
      "icon": "paper-airplane"
    },
    {
      "value": "hangars",
      "label": "Hangars",
      "icon": "building-office-2"
    },
    {
      "value": "account",
      "label": "Account",
      "icon": "user-circle"
    }
  ];
  protected addAircraft(event: unknown): void {
    // Growing the fleet is the operator's main setup task
    console.info('addAircraft', event);
  }

  protected openNotifications(event: unknown): void {
    // New requests and messages
    console.info('openNotifications', event);
  }

  protected exportReport(event: unknown): void {
    // Monthly report for the accountant
    console.info('exportReport', event);
  }

  protected openBooking(event: unknown): void {
    // Sortable, searchable table that scrolls sideways on phones; rows open the booking
    console.info('openBooking', event);
  }
}
