// @page signup SignupPage "Create account"
// Generated by `node tools/page/airiona.mjs scaffold signup` from docs/pages/signup/page.spec.json.
// Change the spec and regenerate; copy this folder into the product app once the page is signed off.
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ArAuthShell, ArButton, ArCheckbox, ArDialog, ArMobileSegmented, ArSuccessBurst, ArTextField, type ArAuthHighlight, type ArOption } from '@airiona/ui';
import { pageForm } from '../../shared/page-form';
import { phone } from '../../shared/validators';
import { SIGNUP_SAMPLE } from './signup.data';

/** Create account. Primary action: Create an account. */
@Component({
  selector: 'pg-signup',
  imports: [ReactiveFormsModule, ArAuthShell, ArButton, ArCheckbox, ArDialog, ArMobileSegmented, ArSuccessBurst, ArTextField],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './signup.page.html',
  styleUrl: './signup.page.css',
})
export class SignupPage {
  private readonly fb = inject(FormBuilder);
  protected readonly data = SIGNUP_SAMPLE;
  protected readonly signup = this.fb.group({
    fullName: ["", [Validators.required, Validators.maxLength(80)]],
    email: ["", [Validators.required, Validators.email, Validators.maxLength(254)]],
    phone: ["", [Validators.required, phone]],
    password: ["", [Validators.required, Validators.minLength(8), Validators.pattern("^(?=.*[A-Za-z])(?=.*\\d).+$")]],
    accountType: ["client", [Validators.required]],
    terms: [false, [Validators.requiredTrue]],
  });
  protected readonly signupForm = pageForm(this.signup, {
    "fullName": {
      "required": "Enter your name.",
      "maxlength": "Names are at most 80 characters."
    },
    "email": {
      "required": "Enter your email.",
      "email": "Enter an email like name@example.com.",
      "maxlength": "Emails are at most 254 characters."
    },
    "phone": {
      "required": "Enter a phone number.",
      "phone": "Enter a number with its country code, like +971 50 123 4567."
    },
    "password": {
      "required": "Choose a password.",
      "minlength": "Use at least 8 characters.",
      "pattern": "Add at least one letter and one number."
    },
    "accountType": {
      "required": "Choose how you will use Airiona."
    },
    "terms": {
      "required": "Accept the terms to create your account."
    }
  });
  protected readonly shellHighlights: ArAuthHighlight[] = [
    {
      "title": "Charter, buy or lease",
      "text": "Request a jet, make an offer on an aircraft or book hangar space from the same account."
    },
    {
      "title": "Verified operators",
      "text": "Every operator and hangar host is checked for certificates and insurance before they list."
    },
    {
      "title": "Pay when it is confirmed",
      "text": "Nothing is charged until the operator confirms your request."
    }
  ];
  protected readonly emailPlaceholder: string = "name@example.com";
  protected readonly accountTypeOptions: Array<string | ArOption> = [
    {
      "value": "client",
      "label": "Traveller"
    },
    {
      "value": "operator",
      "label": "Operator"
    },
    {
      "value": "hangar",
      "label": "Hangar host"
    }
  ];
  protected readonly signupDone = signal(false);
  protected submitSignup(): void {
    this.signupForm.submit((value) => {
      // POST /api/accounts { fullName, email, phone, password, accountType, terms }. On failure: 409 (email exists): message under Email 'An account with this email exists. Sign in instead.'; 422: messages under the fields the server names; network: danger Toast with Retry and the form stays filled
      console.info('signup submit', value);
      this.signupDone.set(true);
    });
  }

  protected openHelp(event: unknown): void {
    // Opens the help centre in a new tab
    console.info('openHelp', event);
  }
}
