// Motion spec for every Airiona component: what moves on hover, press, entry and state change.
// One source for the README "Motion" sections, the library Motion tab and the tracked table.
// [hover, press, enter, change, tokens]
const S = {
  Icon: ["Inherits from its parent (icon buttons scale it 1.08).", "—", "—", "Pressed icons pop 1 → 1.18 → 1.", "duration-slow · ease-spring"],
  Scene: ["—", "—", "Fades in with its card.", "—", "—"],
  Button: ["Lifts 1px; primary and brand get a light sweep across the label and a deeper shadow; the arrow disc turns 45°.", "Scales to 0.97 in duration-instant.", "—", "Loading shows a spinner that turns on a soft curve.", "duration-fast · duration-instant · ease-standard · ease-spring"],
  IconButton: ["Icon scales to 1.08 on a spring.", "Scales to 0.94.", "—", "Toggled on: icon pops. Heart: squash 0.7 → 1.32 → 1 with a red ring bursting outward. Badge pulses three times.", "duration-slow · ease-spring"],
  SegmentedControl: ["Text darkens.", "Item scales to 0.96.", "—", "One indicator slides between options and resizes to the new label (no cross-fade).", "duration-base · ease-standard"],
  Chip: ["Outline strengthens.", "Scales to 0.95.", "—", "Selected: pops to 1.08 and settles, colour fills in duration-fast.", "duration-fast · duration-slow · ease-spring"],
  TextField: ["Border darkens.", "—", "Hint text rises in.", "Error: the field shakes once (380ms, 6px) and the message rises in. Focus ring eases out to 3px.", "duration-fast · ease-standard"],
  Checkbox: ["—", "Box scales to 0.9.", "—", "Checked: box pops and the tick draws itself in 200ms.", "duration-base · ease-spring"],
  Switch: ["—", "Knob stretches to 27px while held.", "—", "Knob slides on a spring; track colour cross-fades.", "duration-base · ease-spring"],
  QuantityStepper: ["Buttons darken.", "Buttons scale to 0.94.", "—", "The number rolls: up from below on +, down from above on −.", "duration-base · ease-enter"],
  Calendar: ["Day tints.", "Day scales to 0.9.", "—", "Month changes slide in from the side you moved toward; picked start and end pop.", "duration-slow · ease-enter · ease-spring"],
  BookingSearch: ["Search button icon tilts and grows.", "Swap scales to 0.92.", "Spotlight follows the cursor across the bar.", "Swap rotates 180° per press on a spring while the airports trade places.", "duration-sheet · ease-spring"],
  Badge: ["—", "—", "—", "Status dot pulses (live, pending).", "2s · ease-standard"],
  Rating: ["—", "—", "—", "—", "—"],
  Toast: ["Timer pauses.", "—", "Rises and scales in; the icon pops 140ms later.", "With `duration`, a hairline timer runs down the bottom edge and closes the toast when it ends.", "duration-slow · ease-enter · linear"],
  BookingSteps: ["—", "—", "Steps stagger in.", "Current dot pops and pulses twice; the connecting line fills.", "duration-slow · ease-spring"],
  Avatar: ["—", "—", "—", "—", "—"],
  AvatarStack: ["The stack fans open (overlap −10px → −4px); a hovered face lifts 3px.", "—", "—", "—", "duration-base · ease-spring"],
  FlightTicket: ["Card lifts 3px; the plane glides forward and back; spotlight follows the cursor.", "—", "—", "—", "duration-slow · 900ms glide"],
  StayCard: ["Card lifts 4px with a deeper shadow; the photo zooms to 1.05 over 700ms; spotlight.", "—", "—", "Saved heart bursts.", "duration-slow · 700ms · ease-standard"],
  DestinationCard: ["Photo zooms to 1.04; the glass plate rises 4px.", "—", "—", "Saved heart bursts.", "700ms · duration-slow"],
  BookingBar: ["Button sweep.", "—", "—", "—", "—"],
  AmenityList: ["—", "—", "Items stagger in, 40ms apart.", "—", "duration-slow · duration-stagger"],
  StatCard: ["Card lifts 3px; spotlight.", "—", "Value counts up from 0; delta rises in after 500ms.", "New values count up again.", "duration-emphasis · ease-out cubic"],
  SideNav: ["Icon nudges 2px right.", "—", "—", "One pill slides vertically to the active item; the active icon pops.", "duration-base · ease-standard"],
  TopNav: ["Link tints.", "—", "—", "The active pill (or underline) slides to the new link and resizes to it.", "duration-base · ease-standard"],
  Dialog: ["—", "—", "Scrim fades and blurs in; panel rises 12px and scales from 0.98; the icon pops.", "Closing plays in reverse: panel sinks and fades in 200ms before unmounting.", "duration-slow in · duration-base out · ease-enter / ease-exit"],
  Select: ["Option tints.", "—", "Options cascade in 22ms apart.", "Chevron flips 180°; the selected check pops.", "duration-base · ease-spring"],
  Menu: ["Item tints.", "—", "Items cascade in 22ms apart.", "—", "duration-base · ease-enter"],
  DataTable: ["Row tints; spotlight on the card.", "—", "Rows stagger in, 28ms apart.", "Sorting, paging and searching replay the row cascade; the bulk bar rises in.", "duration-slow · ease-enter"],
  Tabs: ["Tab tints.", "—", "—", "Ink bar slides; the panel slides in from the side of the new tab.", "duration-base · duration-slow · ease-enter"],
  Tooltip: ["Appears after 350ms (instantly on keyboard focus) and scales in from 0.96.", "—", "—", "—", "duration-fast"],
  DatePicker: ["Day tints.", "—", "Popover drops in.", "Months slide in from the direction you moved.", "duration-slow · ease-enter"],
  MetricTile: ["Spotlight.", "—", "Value counts up; delta rises in.", "—", "duration-emphasis"],
  PillBarChart: ["Pill shows its tip.", "—", "Pills grow up from the axis, 24ms apart; the tip pops in last.", "Active pill pulses twice.", "duration-emphasis · ease-enter"],
  SegmentGauge: ["—", "—", "Arcs draw in; the total counts up.", "—", "duration-emphasis"],
  RatingBreakdown: ["—", "—", "Score counts up; bars grow from the left.", "—", "duration-emphasis"],
  Leaderboard: ["Row slides 4px right.", "—", "Rows stagger in.", "—", "duration-slow · duration-stagger"],
  StripeDistribution: ["—", "—", "Stripes grow up, 24ms apart.", "—", "duration-emphasis"],
  Heatmap: ["Cell scales to 1.06 with a shadow.", "—", "Cells pop in, 18ms apart.", "—", "duration-slow · duration-fast"],
  AbsenceCard: ["Spotlight.", "—", "—", "—", "—"],
  ToggleTile: ["—", "Knob stretches.", "—", "Knob slides on a spring.", "duration-base · ease-spring"],
  ArrivalTile: ["—", "—", "Progress bar grows from the left.", "The plane glints every 2.6s.", "duration-emphasis"],
  RingStatCard: ["Spotlight.", "—", "Ring draws around.", "—", "duration-emphasis"],
  HabitTile: ["—", "—", "Ring draws around.", "—", "duration-emphasis"],
  GateTile: ["Arrow nudges 4px.", "—", "—", "Live dot pulses.", "1.6s"],
  VoiceRecorder: ["—", "—", "—", "While playing, the waveform breathes bar by bar.", "1s loop"],
  BatteryTile: ["—", "—", "Cells fill up, 24ms apart.", "—", "duration-emphasis"],
  MediaPlayer: ["—", "—", "Progress grows from the left.", "—", "duration-emphasis"],
  AnalogClock: ["—", "—", "—", "Second hand ticks with a small spring; the digital readout under the hands updates with it.", "300ms · ease-spring"],
  RecordingTile: ["—", "Button scales to 0.94.", "—", "Recording: the button pulses red.", "1.4s loop"],
  ActivityCalendar: ["Spotlight.", "—", "—", "—", "—"],
  WorldClock: ["—", "—", "—", "Slider settles on a spring.", "duration-base · ease-spring"],
  RideTile: ["Car rolls 6px forward.", "—", "Car drives in from the left.", "—", "900ms · ease-enter"],
  ChargingTile: ["—", "—", "Charge bar grows; a light scans along it.", "Scan repeats every 2.4s while charging.", "duration-emphasis · 2.4s"],
  TripSummaryTile: ["—", "—", "—", "Art floats gently.", "6s loop"],
  Ring: ["—", "—", "Draws from empty to its value.", "Value changes ease along the ring.", "duration-emphasis · duration-slow"],
  ProfileProjectCard: ["—", "—", "Progress grows from the left.", "—", "duration-emphasis"],
  MeetingsStrip: ["Day lifts 2px.", "—", "Days stagger in.", "Picked day pops.", "duration-base · ease-spring"],
  RoadmapGantt: ["—", "—", "Rows stagger in; bars grow from their start.", "—", "duration-emphasis"],
  DateChip: ["—", "—", "—", "—", "—"],
  EfficiencyChart: ["—", "—", "Line draws left to right; the dot and flag pop in at the end.", "—", "duration-emphasis"],
  TotalTimeTile: ["Spotlight.", "—", "Value counts up.", "—", "duration-emphasis"],
  AssistantCard: ["The orb's glow deepens.", "—", "—", "The 3D orb floats.", "6s loop"],
  Notch: ["Buttons in the notch lift 2px.", "Buttons scale to 0.94.", "—", "The cut-out is redrawn when the card resizes.", "duration-fast"],
  ChannelCard: ["Spotlight.", "—", "Amount counts up; line or step chart draws; bars grow.", "Marker and tip pop in at the end.", "duration-emphasis"],
  PromptCard: ["Chips lift 2px; the orb's glow deepens.", "—", "The 3D orb scales in, then floats.", "—", "700ms · ease-spring · 6s float"],
  BalanceChart: ["Bar darkens.", "—", "Value counts up; bars grow.", "One indicator slides between ranges.", "duration-base · duration-emphasis"],
  HoldingsPanel: ["Row tints.", "—", "Rows stagger in.", "—", "duration-slow"],
  SparkBars: ["—", "—", "Bars grow.", "—", "duration-emphasis"],
  PageHeader: ["—", "—", "—", "Tabs slide their indicator.", "duration-base"],
  PilotDashboard: ["Every card has its own spotlight.", "—", "Cards stagger in, row by row; numbers count up; charts draw.", "Nav pill and range indicator slide.", "duration-slow · duration-stagger · duration-emphasis"],
  PhoneFrame: ["—", "—", "—", "—", "—"],
  StatusBar: ["—", "—", "—", "—", "—"],
  AppBar: ["—", "Buttons scale to 0.97.", "Large title rises in.", "—", "duration-page · ease-enter"],
  TabBar: ["—", "Items scale to 0.97.", "—", "Dot, disc or pill slides to the new tab; the icon pops; FAB icon turns 90° on hover.", "duration-base · ease-spring"],
  BottomSheet: ["Handle widens.", "—", "Slides up on the sheet curve; content cascades in after 120ms.", "Drag follows the finger; release past 110px or flick to dismiss; closing slides down in 260ms.", "duration-sheet · ease-sheet · ease-exit"],
  ActionSheet: ["—", "Items scale to 0.97.", "Group slides up; Cancel follows 40ms later.", "—", "duration-sheet · ease-sheet"],
  Fab: ["Icon turns 90°.", "Scales to 0.94.", "—", "—", "duration-slow · ease-spring"],
  StickyActionBar: ["CTA arrow nudges.", "Scales to 0.97.", "Rises in 120ms after the screen.", "—", "duration-page · ease-enter"],
  HeroHeader: ["—", "—", "Title rises; overlapping card follows 80ms later.", "Waves drift slowly; map dots glint.", "duration-page · 18s drift"],
  GreetingBar: ["—", "—", "Greeting rises in.", "—", "duration-page"],
  SearchField: ["—", "—", "—", "Focus ring eases in.", "duration-fast"],
  SectionHeader: ["Action arrow nudges 3px.", "—", "—", "—", "duration-base"],
  ChipScroller: ["—", "Chip scales to 0.97.", "Chips stagger in.", "Selected chip pops.", "duration-slow · ease-spring"],
  SnapCarousel: ["—", "—", "Cards stagger in.", "Cards scale up from 0.94 as they scroll into view (scroll-driven where supported).", "scroll timeline"],
  SwipeRow: ["—", "Action buttons scale to 0.92.", "—", "Row follows the finger; snaps open or shut on the sheet curve.", "260ms · ease-sheet"],
  MobileSegmented: ["—", "Scales to 0.97.", "—", "Thumb slides on a spring.", "duration-base · ease-spring"],
  FieldTile: ["—", "Scales to 0.97.", "—", "—", "duration-instant"],
  ChecklistRow: ["—", "Scales to 0.97.", "—", "Done: box pops, tick draws.", "duration-base · ease-spring"],
  WeekStrip: ["—", "Day scales to 0.97.", "Days stagger in.", "Picked day pops into its pill.", "duration-slow · ease-spring"],
  Timeline: ["—", "—", "Items stagger in.", "The featured node pulses.", "1.6s loop"],
  CalendarCard: ["—", "Day scales to 0.97.", "—", "Month slides.", "duration-slow"],
  AgendaCard: ["Lifts.", "Scales to 0.98.", "Cards stagger in.", "—", "duration-slow"],
  PeoplePicker: ["—", "Scales to 0.97.", "People stagger in.", "Picked person pops.", "duration-slow"],
  MemberPicker: ["Add button turns 90°.", "Scales to 0.97.", "—", "—", "duration-base · ease-spring"],
  FeatureCard: ["Arrow nudges; pattern drifts.", "Scales to 0.98.", "—", "—", "16s drift"],
  CategoryTile: ["Lifts 3px.", "Scales to 0.98.", "Progress bar grows.", "Active tile fills its icon.", "duration-slow"],
  PlanList: ["—", "Scales to 0.97.", "Items stagger in; art floats.", "—", "duration-slow"],
  MiniStatCard: ["Spotlight.", "—", "Value counts up; delta rises.", "—", "duration-emphasis"],
  TripRow: ["Plane glides.", "Scales to 0.97.", "Rows stagger in.", "—", "900ms glide"],
  FlightSearchSheet: ["—", "Swap scales.", "—", "Swap icon turns 180° per press.", "duration-sheet · ease-spring"],
  RouteHeader: ["—", "—", "The globe art settles from 0.96.", "Dashes flow toward the destination; the plane bobs at the apex; airport dots pulse in turn.", "1.2s dash loop · 3.6s bob"],
  TicketCard: ["Lifts 3px; the plane glides.", "Scales to 0.98.", "—", "—", "duration-slow"],
  BoardingPass: ["Lifts with its shadow.", "—", "Rises in; the 3D jet glides in across the fold and then floats; details stagger in; the QR settles from a soft blur and a scan light passes over it twice.", "A small plane flies the dashed route line on a loop.", "duration-page · ease-enter · 4.8s route loop"],
  PlaceCard: ["Photo zooms; plate rises 4px.", "Scales to 0.98.", "—", "Saved heart bursts.", "700ms"],
  PlaceHero: ["—", "—", "Photo settles from 0.96.", "—", "900ms · ease-enter"],
  InfoStatRow: ["—", "—", "Stats stagger in.", "—", "duration-slow"],
  ExpandableText: ["—", "Scales to 0.97.", "—", "The chevron flips 180° on a spring.", "duration-base · ease-spring"],
  MiniDestination: ["Lifts; photo zooms.", "Scales to 0.98.", "—", "—", "700ms"],
  IllustrationCallout: ["Link arrow nudges.", "—", "Art floats.", "—", "6s loop"],
  ActivityFeed: ["—", "—", "Entries stagger in.", "—", "duration-slow"],
  DetailList: ["—", "—", "Rows stagger in.", "—", "duration-slow"],
  LetterRow: ["—", "Scales to 0.97.", "Rows stagger in.", "—", "duration-slow"],
  ProfileHeader: ["—", "—", "—", "—", "—"],
  OnboardingFlow: ["Next button grows 1.06; arrow nudges.", "Next scales to 0.94.", "The art scales in then floats; eyebrow, title and text rise 70ms apart.", "Dots stretch to the active step; the ring fills.", "duration-page · ease-enter · ease-spring"],
  CountUp: ["—", "—", "Counts from 0 to the value, keeping prefix, suffix, decimals and commas.", "Counts again when the value changes. Screen readers get the final value only.", "duration-emphasis · ease-out cubic"],
  SuccessBurst: ["—", "—", "Disc pops, the tick draws, a ring and 14 particles burst, then title and text rise.", "Replay with a new replayKey. Once per flow.", "duration-celebrate · ease-spring"],
  Skeleton: ["—", "—", "—", "Shimmer sweeps left to right every 1.4s until content arrives.", "1.4s linear"],
  RouteTransition: ["—", "—", "Fade-through, shared X (direction-aware), shared Y or scale when the route key changes.", "—", "duration-page · ease-enter"],
  QRCode: ["—", "—", "Settles from a soft blur inside BoardingPass.", "Static once drawn. Never animate a code that is being scanned.", "700ms · ease-enter"],
  ScreenStack: ["—", "—", "Push: new screen slides in from the right while the old one parallaxes 28% left and dims.", "Pop: reverse. The old layer is inert while leaving.", "duration-sheet · ease-sheet"]
};
const MOTION = {};
for (const [k, v] of Object.entries(S)) MOTION[k] = { hover: v[0], press: v[1], enter: v[2], change: v[3], tokens: v[4] };
function motionMd(name) {
  const m = MOTION[name];
  if (!m) return "";
  const rows = [["Hover", m.hover], ["Press", m.press], ["Enter", m.enter], ["State change", m.change], ["Tokens", m.tokens]].filter((r) => r[1] && r[1] !== "—");
  if (!rows.length) return "\n\n## Motion\n\nStatic by design. It takes the motion of the card or screen it sits in.\n";
  return "\n\n## Motion\n\n| Moment | Behaviour |\n|---|---|\n" + rows.map((r) => "| " + r[0] + " | " + r[1] + " |").join("\n") + "\n\nAll motion stops under `prefers-reduced-motion`; state changes still apply instantly.\n";
}
module.exports = { MOTION, motionMd };
